spectaql:
  logoFile: ./logo.png
  displayAllServers: false

introspection:
  url: http://127.0.0.1:8000/graphql
  headers:
    Authorization: Bearer B8BA5D730210B50F41C06941582D7965D57319D5685440587F98DFDC45A01594

extensions:
  graphqlScalarExamples: true

info:
  title: GraphQL DFIR-IRIS DOCUMENTATION
  description: Welcome to DFIR-IRIS GraphQL Documentation. GraphQL is a query language for APIs and a runtime for fulfilling those queries with your existing data.
  x-introItems:
    - title: GraphQL informations
      description: GraphQL provides a complete and understandable description of the data in your API, gives clients the power to ask for exactly what they need and nothing more, makes it easier to evolve APIs over time, and enables powerful developer tools.

servers:
  - url: https://v200.beta.dfir-iris.org/login
    production: true